generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardLog
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_log
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:           [created_at, module, action, url, status_code]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
